export const chemicals = [
  {
    id: "magnesium-sulphate",
    name: "Magnesium Sulphate",
    shortName: "MgSO4",
    formula: "MgSO4.7H2O",
    reaction: "MgO + H2SO4 -> MgSO4 + H2O",
    composition: ["Magnesium as Mg: 9.5-10%", "Sulphur as S: 12-13%", "Water soluble crystals"],
    tagline: "Low-investment fertilizer and pharma salt with steady bulk demand.",
    badges: ["High Demand", "Low Cost", "Beginner Friendly"],
    accent: "leaf",
    definition:
      "A water-soluble magnesium salt used mainly for magnesium and sulphur correction in crops.",
    uses: {
      Agriculture: [
        "Corrects magnesium deficiency",
        "Used in foliar spray, fertigation, and soil application",
        "Supports chlorophyll formation",
      ],
      Industrial: [
        "Textile processing",
        "Magnesium compound production",
        "Specialty process chemical",
      ],
      Other: ["Epsom salt applications", "Food and pharma grades need higher purity"],
    },
    rawMaterials: ["Magnesium oxide or magnesite", "Sulphuric acid", "Process water"],
    manufacturing: [
      "Charge water and controlled sulphuric acid into reactor.",
      "Add magnesium oxide or magnesite slurry slowly.",
      "Maintain pH and temperature for complete neutralization.",
      "Filter insoluble impurities.",
      "Evaporate, crystallize, dry, screen, and pack.",
    ],
    industrialMethod: "Neutralization and crystallization process used by small and mid-size Indian units.",
    plantFlow: ["Raw material input", "Reaction stage", "Filtration", "Evaporation", "Drying", "Packing"],
    plantLayout: ["Raw material storage", "Reactor unit", "Filtration unit", "Drying unit", "Packaging section"],
    machinery: ["Acid storage tank", "Neutralization reactor", "Filter press", "Evaporator", "Crystallizer", "Dryer", "Packing machine"],
    plantUnits: [
      "Acid storage tank",
      "Neutralization reactor",
      "Filter press",
      "Evaporator",
      "Crystallizer",
      "Dryer and packing line",
    ],
    space: {
      land: "5,000-10,000 sq ft",
      expandability: "Easy expansion by adding crystallizer, dryer, and packing capacity.",
    },
    economics: {
      setup: "Rs 20-40 lakh for a small basic plant",
      costDrivers: ["Sulphuric acid price", "Magnesium source purity", "Fuel or steam cost", "Drying efficiency"],
      priceLogic: "Price depends on purity, crystal size, moisture, local logistics, and seasonal farm demand.",
      profitability: "Moderate profitability with broad market access and manageable process complexity.",
    },
    marketInsights: {
      demand: "Broad demand in fertilizer, agri-input, and industrial supply channels.",
      priceRange: "Approx Rs 6-12/kg for bulk fertilizer grade.",
      buyers: ["Fertilizer blenders", "Agri-input dealers", "Pharma and industrial buyers"],
    },
    comparison: {
      cost: "Low",
      demand: "High seasonal",
      profitability: "15-25%",
      ease: "Easy",
      availability: "Good",
      competition: "Medium",
    },
  },
  {
    id: "ferrous-sulphate",
    name: "Ferrous Sulphate",
    shortName: "FeSO4",
    formula: "FeSO4.7H2O",
    reaction: "Fe + H2SO4 -> FeSO4 + H2",
    composition: ["Iron as Fe: 19-20%", "Sulphur as S: 11-12%", "Green crystalline salt"],
    tagline: "Iron salt used in agriculture, water treatment, and industrial applications.",
    badges: ["Low Raw Material Cost", "Utility Chemical", "Stable Demand"],
    accent: "copper",
    definition:
      "A ferrous iron salt used as an iron nutrient, reducing agent, and water-treatment chemical.",
    uses: {
      Agriculture: [
        "Corrects iron chlorosis",
        "Used in micronutrient fertilizer blends",
        "Supports soil nutrition programs",
      ],
      Industrial: [
        "Water and effluent treatment",
        "Cement chromium reduction",
        "Pigment and ferric salt intermediate",
      ],
      Other: ["Feed and pharma grades need strict impurity control", "Laboratory reducing agent"],
    },
    rawMaterials: ["Iron scrap or mill scale", "Sulphuric acid", "Water"],
    manufacturing: [
      "Clean iron scrap or mill scale feedstock.",
      "Digest with diluted sulphuric acid.",
      "Vent hydrogen safely.",
      "Settle and filter undissolved solids.",
      "Crystallize, dry at low heat, and pack quickly.",
    ],
    industrialMethod: "Acid digestion of iron-bearing material followed by settling, crystallization, and drying.",
    plantFlow: ["Raw material input", "Acid digestion", "Gas ventilation", "Filtration", "Drying", "Packing"],
    plantLayout: ["Scrap storage", "Reaction tank", "Ventilation zone", "Filtration unit", "Dryer", "Packaging section"],
    machinery: ["Scrap washer", "Acid digestion tank", "Ventilation system", "Settling tank", "Filter press", "Tray or rotary dryer", "Bagging unit"],
    plantUnits: [
      "Scrap preparation area",
      "Acid digestion tank",
      "Gas ventilation system",
      "Settling tank",
      "Crystallizer",
      "Dryer and bagging unit",
    ],
    space: {
      land: "Around 5,000 sq ft",
      expandability: "Expandable by adding digestion tanks and drying area.",
    },
    economics: {
      setup: "Rs 15-30 lakh for a small plant",
      costDrivers: ["Scrap quality", "Acid consumption", "Oxidation losses", "Moisture control", "Local freight"],
      priceLogic: "Price depends on iron percentage, moisture, impurity limits, and target grade.",
      profitability: "Moderate margins when low-cost feedstock is available nearby.",
    },
    marketInsights: {
      demand: "Steady demand from agriculture, water treatment, and industrial users.",
      priceRange: "Approx Rs 5-10/kg depending on grade and moisture.",
      buyers: ["Water treatment firms", "Fertilizer blenders", "Industrial chemical distributors"],
    },
    comparison: {
      cost: "Low",
      demand: "Steady",
      profitability: "10-20%",
      ease: "Easy",
      availability: "Very good",
      competition: "High",
    },
  },
  {
    id: "potassium-sulphate",
    name: "Potassium Sulphate",
    shortName: "K2SO4",
    formula: "K2SO4",
    reaction: "2KCl + H2SO4 -> K2SO4 + 2HCl",
    composition: ["Potassium as K2O: 50-52%", "Sulphur as S: 17-18%", "Chloride-free potash fertilizer"],
    tagline: "Premium chloride-free potash fertilizer for high-value and export crops.",
    badges: ["Export Oriented", "Premium Fertilizer", "Higher Capex"],
    accent: "river",
    definition:
      "A chloride-free potassium fertilizer used for premium and chloride-sensitive crops.",
    uses: {
      Agriculture: [
        "Grapes, pomegranate, tea, tobacco, spices, and fruits",
        "Chloride-sensitive crop nutrition",
        "High-value fertigation programs",
      ],
      Industrial: ["Specialty fertilizer blends", "Limited glass and chemical applications"],
      Other: ["Premium retail fertilizer markets", "Customized crop nutrition products"],
    },
    rawMaterials: ["Potassium chloride", "Sulphuric acid", "Fuel or heat source", "HCl absorption media"],
    manufacturing: [
      "Feed KCl and sulphuric acid into high-temperature reaction system.",
      "Run Mannheim-type furnace reaction.",
      "Capture HCl gas through scrubber or absorber.",
      "Cool, crush, grind, and screen product.",
      "Test chloride, potassium content, moisture, and particle size.",
    ],
    industrialMethod: "Mannheim furnace route with HCl gas recovery and strong pollution-control systems.",
    plantFlow: ["Raw material input", "High-temperature reaction", "Gas scrubbing", "Cooling", "Grinding", "Packing"],
    plantLayout: ["KCl storage", "Acid storage", "Furnace area", "HCl scrubber", "Cooling and grinding", "Packaging section"],
    machinery: ["KCl handling system", "Sulphuric acid tank", "Mannheim furnace", "HCl scrubber", "Cooler", "Crusher", "Screen", "Packing line"],
    plantUnits: [
      "KCl handling system",
      "Sulphuric acid storage",
      "High-temperature furnace",
      "HCl gas scrubber",
      "Cooling and grinding line",
      "Granulation or packing section",
    ],
    space: {
      land: "20,000+ sq ft",
      expandability: "Expansion needs furnace, scrubber, utilities, and compliance planning.",
    },
    economics: {
      setup: "Rs 2-5 crore or more depending on furnace, scrubber, and capacity",
      costDrivers: ["KCl supply price", "Fuel cost", "Scrubber reliability", "HCl by-product value", "Environmental compliance"],
      priceLogic: "Premium pricing depends on low chloride level, crop demand, and soluble grade specification.",
      profitability: "High potential, but capex and gas handling risks are significant.",
    },
    marketInsights: {
      demand: "Premium demand from high-value crop regions and export-oriented farming.",
      priceRange: "Approx Rs 35-60/kg depending on soluble grade and purity.",
      buyers: ["Fertilizer companies", "Export crop growers", "Agri distributors"],
    },
    comparison: {
      cost: "High",
      demand: "Premium niche",
      profitability: "20-35%",
      ease: "Hard",
      availability: "Moderate",
      competition: "Medium",
    },
  },
  {
    id: "zinc-sulphate-monohydrate",
    name: "Zinc Sulphate Monohydrate",
    shortName: "ZnSO4",
    formula: "ZnSO4.H2O",
    reaction: "ZnO + H2SO4 -> ZnSO4 + H2O",
    composition: ["Zinc as Zn: 33%", "Sulphur as S: 15%", "Low-moisture granular or powder grade"],
    tagline: "High-demand zinc micronutrient fertilizer for Indian soils and agri-input markets.",
    badges: ["Micronutrient", "High Demand", "Farmer Focus"],
    accent: "zinc",
    definition:
      "A zinc micronutrient salt used mainly to correct zinc deficiency in crops.",
    uses: {
      Agriculture: [
        "Major micronutrient fertilizer for zinc-deficient soils",
        "Used in basal application and fertilizer blends",
        "Supports crop growth, grain filling, and yield quality",
      ],
      Industrial: [
        "Electroplating and metal treatment",
        "Chemical intermediate",
        "Feed and specialty grades with strict quality norms",
      ],
      Other: ["Retail agri packs", "Micronutrient mixtures", "Water-soluble fertilizer blends"],
    },
    rawMaterials: ["Zinc oxide", "Sulphuric acid", "Process water", "Filter aid or settling aid"],
    manufacturing: [
      "Prepare zinc oxide slurry with process water.",
      "Add controlled sulphuric acid in reactor.",
      "Maintain pH, temperature, and reaction time.",
      "Filter insoluble residue and heavy impurities.",
      "Concentrate liquor and dry to monohydrate grade.",
      "Screen, test Zn content, and pack.",
    ],
    industrialMethod: "Neutralization of zinc oxide with sulphuric acid followed by filtration, concentration, drying, and packing.",
    plantFlow: ["Raw material input", "Reaction stage", "Filtration", "Concentration", "Drying", "Packing"],
    plantLayout: ["Zinc oxide storage", "Acid storage", "Reactor unit", "Filtration unit", "Drying unit", "Packaging section"],
    machinery: ["Zinc oxide storage hopper", "Sulphuric acid tank", "Reactor", "Filter press", "Evaporator or concentrator", "Dryer", "Sifter", "Packing machine"],
    plantUnits: [
      "Zinc oxide storage",
      "Sulphuric acid tank",
      "Neutralization reactor",
      "Filter press",
      "Concentrator",
      "Dryer and packing line",
    ],
    space: {
      land: "7,000-12,000 sq ft",
      expandability: "Good expansion scope through extra reactors, dryer capacity, and packing automation.",
    },
    economics: {
      setup: "Rs 35-70 lakh for a practical small to mid-size unit",
      costDrivers: ["Zinc oxide price", "Sulphuric acid price", "Zn percentage compliance", "Drying fuel", "Dealer credit cycle"],
      priceLogic: "Pricing follows Zn percentage, particle size, moisture, packaging size, and agri-season demand.",
      profitability: "Good potential because zinc deficiency is common and micronutrient buyers value consistent Zn content.",
    },
    marketInsights: {
      demand: "Strong demand in Indian agriculture due to zinc-deficient soils and micronutrient adoption.",
      priceRange: "Approx Rs 45-90/kg depending on Zn percentage, grade, pack size, and brand.",
      buyers: ["Fertilizer companies", "Farmers", "Agri-input distributors", "Micronutrient mixture units"],
    },
    comparison: {
      cost: "Medium",
      demand: "High",
      profitability: "18-30%",
      ease: "Medium",
      availability: "Good",
      competition: "High",
    },
  },
];

export const comparisonRows = chemicals.map((chemical) => ({
  chemical: chemical.name,
  cost: chemical.comparison.cost,
  demand: chemical.comparison.demand,
  profitability: chemical.comparison.profitability,
  ease: chemical.comparison.ease,
  availability: chemical.comparison.availability,
  competition: chemical.comparison.competition,
}));

export const platformStats = [
  { label: "Core chemicals", value: "4" },
  { label: "Plant units mapped", value: "24+" },
  { label: "India focus", value: "100%" },
];

export const processStats = [
  { label: "Process flows", value: "4" },
  { label: "Layout zones", value: "20+" },
  { label: "Machinery groups", value: "25+" },
];
